"""
languages:
  - code: en
    name: English

steps: [11, 12] # Default to running the text processing and chat processing examples

data_sources: {}
llm_settings:
  model: "gpt-4o"
  temperature: 0.7
"""