"""
languages:
  - code: en
    name: English

steps: [13] # Default to running the basic chat flow

data_sources: {}

chat_settings:
  example_message: "The user is asking about booking a flight."
  recent_memory_window_minutes: 10
"""