languages:
  - code: en
    name: English
  - code: de
    name: German

steps: [1, 2, 3, 5, 6, 7, 8, 9, 10]

data_sources:
  - name: DBpedia
    uri: http://dbpedia.org/
  - name: Wikidata
    uri: https://www.wikidata.org/
  - name: YAGO
    uri: https://yago-knowledge.org/
  - name: Wikipedia
    uri: https://en.wikipedia.org/